version: 0.0
Resources:
  - codedeploy-lab-function:
      Type: AWS::Lambda::Function
      Properties:
        Name: codedeploy-lab-function
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2